// "use client";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0b0f19] text-white">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
